# Generated by Django 5.2.1 on 2025-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descenttype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this descent type is active and can be selected.'),
        ),
    ]
