# Generated by Django 5.2.1 on 2025-05-28 00:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='prompt',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='descentsession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='response',
        ),
        migrations.AddField(
            model_name='descentsession',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descentsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='descentsession',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='descenttype',
            name='type',
            field=models.CharField(choices=[('EMOTIONAL', 'Emotional'), ('MENTAL', 'Mental'), ('SPIRITUAL', 'Spiritual'), ('PHYSICAL', 'Physical'), ('EXISTENTIAL', 'Existential')], default=datetime.datetime(2025, 5, 28, 0, 28, 22, 518420, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='emotion_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='entry',
            name='reflection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ritual',
            name='instructions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.descentsession'),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='type',
            field=models.CharField(choices=[('PRE', 'Pre-Descent'), ('DURING', 'During Descent'), ('POST', 'Post-Descent')], max_length=20),
        ),
    ]
