# Generated by Django 5.2.1 on 2025-05-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_prompt_entry_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descenttype',
            options={'ordering': ['name'], 'verbose_name': 'Descent Type', 'verbose_name_plural': 'Descent Types'},
        ),
        migrations.RemoveField(
            model_name='descenttype',
            name='updated_at',
        ),
    ]
