# Generated by Django 5.2.1 on 2025-05-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_descenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='descent_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rituals', to='journal.descenttype'),
        ),
    ]
